### PR TITLE
Shallow clone submodules by default

### PR DESCRIPTION
**Pull request by 6543**
got a pipeline (non public) from 12:35min down to 3:03min !!!

---
*Sponsored by Kithara Software GmbH*

### CODE REVIEW

**Comment by 6543** [comment]
# Before
image
# After
image

**Comment by pat-s** [comment]
Should this behavior (and other custom defaults) be documented somewhere? I guess a high-level overview of how the default cloning is happening could go into https://github.com/woodpecker-ci/plugin-git/blob/main/docs.md and into https://woodpecker-ci.org/docs/next/usage/workflow-syntax#clone?

**Comment by 6543** [comment]
we already document the defaults!!!

in docs.md

**Comment by 6543** [comment]
image

**Review by lafriks — APPROVED** [review]

**Pull request merged**
