### PR TITLE
Reduce image platforms

### PR DESCRIPTION
**Pull request by pat-s**
`riscv64` does not even have a alpine build for the latest release.
I guess we don't need to support all exotic platforms? Also arm/v6 is quite old and probably not used by anyone anymore.

Fixes issues in #90

### CODE REVIEW

**Comment by lafriks** [comment]
alpine supports riscv64 only on edge because it's support is still in development for it to be considered stable. As for RISC-V itself it's gaining popularity as cheaper more power efficient alternative for ARM especially for embedded devices etc. I would vote to not drop it

**Comment by pat-s** [comment]
I see the argument but then we would need to apply this to all other images as well. We also don't have images for riskv for server and agent.

Why not wait until 3.19 and then apply it to all? Having it only for the git plugin doesn't make much sense - unless I am missing something.
And if we're running on `edge` here and not anywhere else, we are out of line with all other images.

**Comment by pat-s** [comment]
More opinions here? @woodpecker-ci/maintainers

**Comment by anbraten** [comment]
Not sure if anyone is seriously (not just for fun in a homelab) using it. Still a pretty rare arch in general

**Comment by pat-s** [comment]
OK, I guess we need a vote. Please thumbs up or down if we should reduce the image platforms as suggested or not @woodpecker-ci/maintainers 

(NB: we can add riscv at any time again if one requests it or when alpine officially supports it)

**Comment by lafriks** [comment]
Currently I'm also not using it so I don't mind but I definitely plan to use it in the future

**Review by 6543 — CHANGES_REQUESTED** [review]
I'll use riscv64 if you need acces just tell

**Comment by 6543** [comment]
As for old arm platforms we can drop that

**Comment by xoxys** [comment]
As long as there is no real issue I dont really understand why we want to drop platform support. Why do we want to "kick out" people that might use older Raspberries with armv6 without having the need to do so?

**Comment by pat-s** [comment]
Resources/runtime. But I agree that older PIs might be a valid target.

Let's keep it as is then. See also https://github.com/woodpecker-ci/plugin-git/pull/90#issuecomment-1749688368. But overall not just blindly building for any platform might certainly help in the long run IMO (resources, environment, etc.). Not just for a few images here but as a general thought.

**Pull request closed without merging**
