### PR TITLE
fix dockerfile to build correct go binary

### PR DESCRIPTION
**Pull request by abc3354**
Removed 2 superfluous lines from docker/Dockerfile.multiarch that caused undefined environment variables in the Makefile which caused amd64 go builds in all cases

More details on https://github.com/woodpecker-ci/woodpecker/issues/1443

### CODE REVIEW

**Comment by lafriks** [comment]
Why is ARG home removed?

**Comment by abc3354** [comment]
Because it is still at line 11

Since the duplicated line for TARGEOS and TARGETARCH created a bug I though it was the same for HOME

I didn't test it though, I will do it now

**Comment by abc3354** [comment]
Ok I searched a little but I have no idea how the HOME arg should be used :/
And I just realized that I deleted the default value (/app) of the argument

Any help on the subject would be appreciated

**Comment by lafriks** [comment]
@6543 can you help on this?

**Comment by anbraten** [comment]
Have a look at https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

**Comment by anbraten** [comment]
For home I would just add the default to the lower arg home line.

**Comment by abc3354** [comment]
I spend some time in the docs to understand the arguments coming from buildx and their scopes, see:
- https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope for an explanation of where the args come from
- https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds for an explanation of the scope of the args

Same conclusion as @anbraten :
- declaring TARGETOS and TARGETARCH in the global scope was overriding the values coming from buildx
- we should be fine using only the ARG HOME in the relevant build step since it is only used here, I will add the default value that I accidentally deleted

Since the ARG HOME is not at the top of the file anymore it is less visible, I could maybe add a line in the README.md about it ?

**Review by anbraten — APPROVED** [review]

**Comment by 6543** [comment]
hah that it was - thanks :heart:

**Pull request merged**
