### PR TITLE
Automatically load tags when executed from tag pipeline

### PR DESCRIPTION
**Pull request by anbraten**
Fixes https://codeberg.org/Codeberg-CI/feedback/issues/53

### CODE REVIEW

**Comment by anbraten** [comment]
I am not sure if it really works this way as we use `BoolFlag` and that uses `strconv.ParseBool` internally. So in our case it would evaluate an empty or the tag name, but that is not a boolean string, right?

**Comment by 6543** [comment]
Yes this likely fails ...

**Comment by 6543** [comment]
... better add code that check if != len(0)

And document it

**Comment by anbraten** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1110

**Pull request closed without merging**
