### PR TITLE
Fix alpine version to 3.18

### PR DESCRIPTION
**Pull request by pat-s**
Or is `edge` really needed?

### CODE REVIEW

**Comment by pat-s** [comment]
What? Strange. It has all platforms... 🤔

**Comment by pat-s** [comment]
Ah `riscv65` is missing...

I don't think we should build for all exotic platforms? Doing a pull...

**Comment by 6543** [comment]
Me is targeting `riscv64`  ... and it will be a stable platform in the next stable debian ... alpine is also following asap everything is ported i guess (dont pin me down on that. i can upstream if desired)

I dont see any issue with using edge as base image ...

Why was this issue created in the first time?

**Comment by pat-s** [comment]
`renovate` is not versioning `:edge` or `:latest`. And I was harmonizing tags across all repos and this one is/was the only one which didn't had `alpine:3.18`.

Ahh I see we have riscv images for release versions. Now I understand...

**Comment by pat-s** [comment]
Then let's switch for the next alpine version 🙂

**Comment by xoxys** [comment]
> renovate is not versioning :edge or :latest

You can enable digest pinning in those cases to still get updated images in case the upstream image was rebuilt.

**Comment by pat-s** [comment]
Good idea. However, this comes with the following downsides:

- latest/edge images are often updated daily (not in the case of alpine it seems so it might be a valid solution here)
- AFAIK you cannot pin the digest of a manifest but only of a certain arch image (this would not be a blocker but usually one would not want to insert an arch-lock due to digest pinning)

But I guess we can just leave it as-is - the discussion needs more energy than the change would be worth it :)

**Comment by xoxys** [comment]
Pinning manifests works as well if I remember correctly. To avoid noise a weekly schedule could be added. But we can also just leave it as it is.

**Comment by 6543** [comment]
well pinning to a specific base image makes it more deterministic ... thats not a bad idea ...

PS: `3.18` is also a moving target :D and we could be more specific there too ...

**Pull request closed without merging**
